# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mining.ui'
#
# Created: Tue Jan  6 16:53:46 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_window(object):
    def setupUi(self, window):
        window.setObjectName(_fromUtf8("window"))
        window.resize(919, 682)
        self.centralwidget = QtGui.QWidget(window)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Shape = QtGui.QWidget()
        self.Shape.setObjectName(_fromUtf8("Shape"))
        self.layoutWidget = QtGui.QWidget(self.Shape)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 149, 341))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.t1 = QtGui.QLineEdit(self.layoutWidget)
        self.t1.setObjectName(_fromUtf8("t1"))
        self.verticalLayout_2.addWidget(self.t1)
        self.t2 = QtGui.QLineEdit(self.layoutWidget)
        self.t2.setObjectName(_fromUtf8("t2"))
        self.verticalLayout_2.addWidget(self.t2)
        self.t3 = QtGui.QLineEdit(self.layoutWidget)
        self.t3.setObjectName(_fromUtf8("t3"))
        self.verticalLayout_2.addWidget(self.t3)
        self.t4 = QtGui.QLineEdit(self.layoutWidget)
        self.t4.setObjectName(_fromUtf8("t4"))
        self.verticalLayout_2.addWidget(self.t4)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.b1 = QtGui.QLineEdit(self.layoutWidget)
        self.b1.setObjectName(_fromUtf8("b1"))
        self.verticalLayout_2.addWidget(self.b1)
        self.b2 = QtGui.QLineEdit(self.layoutWidget)
        self.b2.setObjectName(_fromUtf8("b2"))
        self.verticalLayout_2.addWidget(self.b2)
        self.b3 = QtGui.QLineEdit(self.layoutWidget)
        self.b3.setObjectName(_fromUtf8("b3"))
        self.verticalLayout_2.addWidget(self.b3)
        self.b4 = QtGui.QLineEdit(self.layoutWidget)
        self.b4.setObjectName(_fromUtf8("b4"))
        self.verticalLayout_2.addWidget(self.b4)
        self.submit = QtGui.QPushButton(self.layoutWidget)
        self.submit.setObjectName(_fromUtf8("submit"))
        self.verticalLayout_2.addWidget(self.submit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.widget = QtGui.QWidget(self.layoutWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout.addWidget(self.widget)
        self.tabWidget.addTab(self.Shape, _fromUtf8(""))
        self.criticalJS = QtGui.QWidget()
        self.criticalJS.setObjectName(_fromUtf8("criticalJS"))
        self.groupBox_3 = QtGui.QGroupBox(self.criticalJS)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 531, 251))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 201, 221))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 121, 167))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.lineEdit_4 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_5 = QtGui.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 301, 241))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 140, 121, 95))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 251, 101))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_8 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_6 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_9 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_7 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_10 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_10)
        self.lineEdit_8 = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_8)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 101, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.groupBox_4 = QtGui.QGroupBox(self.criticalJS)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 270, 531, 271))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(250, 293, 63, 27))
        self.lineEdit_20.setText(_fromUtf8(""))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.widget1 = QtGui.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(20, 40, 498, 217))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_15 = QtGui.QLabel(self.widget1)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.lineEdit_15 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_15.setText(_fromUtf8(""))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.gridLayout.addWidget(self.lineEdit_15, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_13 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_13.setText(_fromUtf8(""))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.gridLayout.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.widget1)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 1, 3, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.widget1)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout.addWidget(self.pushButton_9, 5, 3, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(self.widget1)
        self.checkBox_10.setText(_fromUtf8(""))
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridLayout.addWidget(self.checkBox_10, 2, 6, 1, 1)
        self.lineEdit_9 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_9.setText(_fromUtf8(""))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.gridLayout.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.widget1)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.lineEdit_14 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_14.setText(_fromUtf8(""))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.gridLayout.addWidget(self.lineEdit_14, 2, 2, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.widget1)
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 1, 4, 1, 1)
        self.label_21 = QtGui.QLabel(self.widget1)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 4, 0, 1, 1)
        self.lineEdit_10 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_10.setText(_fromUtf8(""))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.gridLayout.addWidget(self.lineEdit_10, 1, 2, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(self.widget1)
        self.checkBox_9.setText(_fromUtf8(""))
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridLayout.addWidget(self.checkBox_9, 1, 6, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget1)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.widget1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 0, 4, 1, 1)
        self.label_20 = QtGui.QLabel(self.widget1)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 3, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.widget1)
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridLayout.addWidget(self.checkBox_2, 2, 4, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.widget1)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 4, 3, 1, 1)
        self.lineEdit_17 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_17.setText(_fromUtf8(""))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.gridLayout.addWidget(self.lineEdit_17, 5, 1, 1, 1)
        self.lineEdit_19 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_19.setText(_fromUtf8(""))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.gridLayout.addWidget(self.lineEdit_19, 4, 2, 1, 1)
        self.lineEdit_18 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_18.setText(_fromUtf8(""))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.gridLayout.addWidget(self.lineEdit_18, 3, 2, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.widget1)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 3, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(self.widget1)
        self.checkBox_6.setText(_fromUtf8(""))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridLayout.addWidget(self.checkBox_6, 4, 4, 1, 1)
        self.lineEdit_22 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_22.setText(_fromUtf8(""))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.gridLayout.addWidget(self.lineEdit_22, 5, 2, 1, 1)
        self.lineEdit_16 = QtGui.QLineEdit(self.widget1)
        self.lineEdit_16.setText(_fromUtf8(""))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.gridLayout.addWidget(self.lineEdit_16, 4, 1, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(self.widget1)
        self.checkBox_7.setText(_fromUtf8(""))
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridLayout.addWidget(self.checkBox_7, 5, 4, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(self.widget1)
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridLayout.addWidget(self.checkBox_5, 3, 4, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(self.widget1)
        self.checkBox_11.setText(_fromUtf8(""))
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridLayout.addWidget(self.checkBox_11, 3, 6, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(self.widget1)
        self.checkBox_12.setText(_fromUtf8(""))
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridLayout.addWidget(self.checkBox_12, 4, 6, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(self.widget1)
        self.checkBox_13.setText(_fromUtf8(""))
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridLayout.addWidget(self.checkBox_13, 5, 6, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(self.widget1)
        self.checkBox_8.setText(_fromUtf8(""))
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridLayout.addWidget(self.checkBox_8, 1, 5, 1, 1)
        self.label_43 = QtGui.QLabel(self.widget1)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 0, 6, 1, 1)
        self.textBrowser = QtGui.QTextBrowser(self.criticalJS)
        self.textBrowser.setGeometry(QtCore.QRect(590, 390, 141, 61))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.tabWidget.addTab(self.criticalJS, _fromUtf8(""))
        self.FactorA = QtGui.QWidget()
        self.FactorA.setObjectName(_fromUtf8("FactorA"))
        self.tabWidget.addTab(self.FactorA, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        window.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(window)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        window.setStatusBar(self.statusbar)

        self.retranslateUi(window)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        window.setWindowTitle(_translate("window", "MainWindow", None))
        self.tabWidget.setToolTip(_translate("window", "<html><head/><body><p><br/></p></body></html>", None))
        self.label.setText(_translate("window", "Top", None))
        self.label_2.setText(_translate("window", "Bottom", None))
        self.submit.setText(_translate("window", "Submit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Shape), _translate("window", "Shape", None))
        self.groupBox_3.setTitle(_translate("window", "Q\' Rating", None))
        self.groupBox.setTitle(_translate("window", "Rock Face Q\'", None))
        self.label_3.setText(_translate("window", "Back =", None))
        self.label_4.setText(_translate("window", "S wall =", None))
        self.label_5.setText(_translate("window", "E wall =", None))
        self.label_6.setText(_translate("window", "N wall =", None))
        self.label_7.setText(_translate("window", "N wall =", None))
        self.groupBox_2.setTitle(_translate("window", "Project Q\' Range", None))
        self.pushButton_4.setText(_translate("window", "Minimum", None))
        self.pushButton_3.setText(_translate("window", "Most Likely", None))
        self.pushButton_2.setText(_translate("window", "Maximum", None))
        self.label_8.setText(_translate("window", "Minimum:", None))
        self.label_9.setText(_translate("window", "Most Likely:", None))
        self.label_10.setText(_translate("window", "Maximum:", None))
        self.pushButton.setText(_translate("window", "Assist", None))
        self.label_11.setText(_translate("window", "Set as Default:", None))
        self.groupBox_4.setTitle(_translate("window", "Critical Joint Set", None))
        self.label_15.setText(_translate("window", "S wall =", None))
        self.label_13.setText(_translate("window", "Dip", None))
        self.label_12.setText(_translate("window", "Back=", None))
        self.pushButton_5.setText(_translate("window", "Assist", None))
        self.pushButton_9.setText(_translate("window", "Assist", None))
        self.pushButton_6.setText(_translate("window", "Assist", None))
        self.label_21.setText(_translate("window", "N wall =", None))
        self.label_22.setText(_translate("window", "W wall =", None))
        self.label_24.setText(_translate("window", "Worst Case", None))
        self.label_20.setText(_translate("window", "E wall", None))
        self.pushButton_8.setText(_translate("window", "Assist", None))
        self.pushButton_7.setText(_translate("window", "Assist", None))
        self.label_14.setText(_translate("window", "Direction", None))
        self.label_43.setText(_translate("window", "Examine Face", None))
        self.textBrowser.setHtml(_translate("window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select faces to be used for the stope analysis</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.criticalJS), _translate("window", "Critical JS and Q\'", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FactorA), _translate("window", "Factor A", None))

